### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by XENOX-GRIX** [aakashg339/Distributed-Systems-Assignment-1-Customizable-Load-Balancer#4]
Need to add the dockerFile so that the load-balancer runs within the container itself.

**Comment by aakashg339** [comment]
Fixed the docker-compose issue. 
Details about the issue
container and network was getting created as <parent folder name>_<container name> and <parent folder name>_<network name>.
Solution 
Added below lines
For load balancer
container_name: loadbalancerContainer
For network below were added
name: my_network - For name
    external: true - So that if network exists then do not create.

**Comment by aakashg339** [comment]
To run kindly use below
1. Using docker-compose - make run_compose
2. Without using docker-compose - make run
